# Лабораторная работа №1
## Выполнил студент группы БФИ2201 Лопеш Сениксон Сандро


### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [1]:
print('Hello, World!')

Hello, World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [2]:
import numpy as np

def generate_random_matrix(user_m=3, user_n=3, user_min_limit=1, user_max_limit=10):
    return np.random.randint(user_min_limit, user_max_limit, size=(user_n, user_m))

In [4]:
user_m = int(input("Digite o numero das colunas: "))
user_n = int(input("digite o numero das linhas: "))
user_min_limit = int(input("Digite o numero minimo do array: "))
user_max_limit = int(input("Digite o numero maximo do array :"))

matrix = generate_random_matrix(user_m, user_n, user_min_limit, user_max_limit)
print(matrix)

Digite o numero das colunas:  6
digite o numero das linhas:  6
Digite o numero minimo do array:  1
Digite o numero maximo do array : 10


[[8 3 2 5 2 7]
 [3 1 8 2 2 8]
 [9 4 2 8 3 1]
 [8 6 2 1 8 5]
 [6 8 3 8 2 8]
 [9 7 6 1 3 3]]


### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [5]:
# Сортировка выбором.
import numpy as np
import time
start_time = time.time()
def selection_sort(arr):
    for i in range(0, len(arr) - 1):
        smallest = i
        for j in range(i + 1, len(arr)):
            if arr[j] < arr[smallest]:
                smallest = j
        arr[i], arr[smallest] = arr[smallest], arr[i]
    return arr

# Пример использования:
def generate_random_matrix(user_matrix_element, user_min_limit=1, user_max_limit=10):
    return np.random.randint(user_min_limit, user_max_limit, size=(user_matrix_element))

user_matrix_element = int(input("Введите количество Элементы: "))
user_min_limit = int(input("Введите минимальный номер массива: "))
user_max_limit = int(input("Введите максимальное число в массиве :"))

matrix = generate_random_matrix(user_matrix_element, user_min_limit, user_max_limit)
print("оригинал массива")
print(matrix)

print("упорядоченный массив по Сортировка выбором")
sorted_arr = selection_sort(matrix)
print(sorted_arr)

print("tempo {}".format(round(time.time() - start_time)*1000))

Введите количество Элементы:  10
Введите минимальный номер массива:  1
Введите максимальное число в массиве : 10


оригинал массива
[2 7 4 6 4 5 5 5 4 9]
упорядоченный массив по Сортировка выбором
[2 4 4 4 5 5 5 6 7 9]
tempo 14000


In [6]:
# Сортировка вставкой.
import numpy as np
import time
start_time = time.time()

def insertion_sort(array):
    n = len(array)
    for i in range(1, n):
        x = array[i]
        j = i
        while j > 0 and array[j - 1] > x:
            array[j] = array[j - 1]
            j -= 1
        array[j] = x
    return array

# Пример использования:
def generate_random_matrix(user_matrix_element, user_min_limit=1, user_max_limit=10):
    return np.random.randint(user_min_limit, user_max_limit, size=(user_matrix_element))

user_matrix_element = int(input("Введите количество Элементы: "))
user_min_limit = int(input("Введите минимальный номер массива: "))
user_max_limit = int(input("Введите максимальное число в массиве :"))

matrix = generate_random_matrix(user_matrix_element, user_min_limit, user_max_limit)
print("оригинал массива")
print(matrix)

print("упорядоченный массив по Сортировка вставкой")
sorted_array = insertion_sort(matrix)
print(sorted_array)

print("tempo {}".format(round(time.time() - start_time)*1000))

Введите количество Элементы:  20
Введите минимальный номер массива:  1
Введите максимальное число в массиве : 15


оригинал массива
[ 9 10  5  3 11  9 13 10  9 11  3 11 14  9  6  7 14  8  1  7]
упорядоченный массив по Сортировка вставкой
[ 1  3  3  5  6  7  7  8  9  9  9  9 10 10 11 11 11 13 14 14]
tempo 17000


In [7]:
# Сортировка обменом. || Сортировка пузырьком.
import numpy as np
import time
start_time = time.time()

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

def generate_random_matrix(user_matrix_element, user_min_limit=1, user_max_limit=10):
    return np.random.randint(user_min_limit, user_max_limit, size=(user_matrix_element))

user_matrix_element = int(input("Введите количество Элементы: "))
user_min_limit = int(input("Введите минимальный номер массива: "))
user_max_limit = int(input("Введите максимальное число в массиве :"))

matrix = generate_random_matrix(user_matrix_element, user_min_limit, user_max_limit)
print("оригинал массива")
print(matrix)

print("упорядоченный массив по Сортировка обменом")
sorted_array = bubble_sort(matrix)
print(sorted_array)

print("tempo {}".format(round(time.time() - start_time)*1000))

Введите количество Элементы:  10
Введите минимальный номер массива:  20
Введите максимальное число в массиве : 30


оригинал массива
[25 22 21 25 22 24 21 26 26 28]
упорядоченный массив по Сортировка обменом
[21 21 22 22 24 25 25 26 26 28]
tempo 13000


In [8]:
# Сортировка Шелла.
import numpy as np
import time
start_time = time.time()

def shellSort(data, length):
    gap = length // 2
    while gap > 0:
        for iIndex in range(gap, length):
            temp = data[iIndex]
            jIndex = iIndex
            while jIndex >= gap and data[jIndex - gap] > temp:
                data[jIndex] = data[jIndex - gap]
                jIndex -= gap
            data[jIndex] = temp
        gap //= 2
    return data

def generate_random_matrix(user_matrix_element, user_min_limit=1, user_max_limit=10):
    return np.random.randint(user_min_limit, user_max_limit, size=(user_matrix_element))

user_matrix_element = int(input("Введите количество Элементы: "))
user_min_limit = int(input("Введите минимальный номер массива: "))
user_max_limit = int(input("Введите максимальное число в массиве :"))

matrix = generate_random_matrix(user_matrix_element, user_min_limit, user_max_limit)
print("оригинал массива")
print(matrix)

print("упорядоченный массив по Сортировка Шелла")
sorted_array = shellSort(matrix, user_matrix_element)
print(sorted_array)

print("tempo {}".format(round(time.time() - start_time)*1000))

Введите количество Элементы:  10
Введите минимальный номер массива:  50
Введите максимальное число в массиве : 80


оригинал массива
[70 53 69 55 74 56 59 74 74 77]
упорядоченный массив по Сортировка Шелла
[53 55 56 59 69 70 74 74 74 77]
tempo 17000


In [9]:
# Быстрая сортировка.
#import random
import numpy as np
import time
start_time = time.time()

def quicksort(nums, fst, lst):
    if fst >= lst:
        return
    i, j = fst, lst
    pivot = nums[np.random.randint(fst, lst)]
    while i <= j:
        while nums[i] < pivot:
            i += 1
        while nums[j] > pivot:
            j -= 1
        if i <= j:
            nums[i], nums[j] = nums[j], nums[i]
            i, j = i + 1, j - 1
    quicksort(nums, fst, j)
    quicksort(nums, i, lst)


def generate_random_matrix(user_matrix_element, user_min_limit=1, user_max_limit=10):
    return np.random.randint(user_min_limit, user_max_limit, size=(user_matrix_element))

user_matrix_element = int(input("Введите количество Элементы: "))
user_min_limit = int(input("Введите минимальный номер массива: "))
user_max_limit = int(input("Введите максимальное число в массиве :"))

matrix = generate_random_matrix(user_matrix_element, user_min_limit, user_max_limit)
print("Оригинал массива")
print(matrix)

print("\nОтсортированный массив по Быстрая сортировка")
sorted_array = quicksort(matrix, 0, len(matrix) - 1)
print(matrix)

print("--- {0} ms ---".format(round(time.time() - start_time)*1000))

    

Введите количество Элементы:  10
Введите минимальный номер массива:  0
Введите максимальное число в массиве : 20


Оригинал массива
[ 7 13 11  9 10  2 12  0 11 18]

Отсортированный массив по Быстрая сортировка
[ 0  2  7  9 10 11 11 12 13 18]
--- 9000 ms ---


In [10]:
# Турнирная сортировка.
import time
import numpy as np
start_time = time.time()

def tournament_sort(arr):
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    left_half = arr[:mid]
    right_half = arr[mid:]

    left_half = tournament_sort(left_half)
    right_half = tournament_sort(right_half)

    return merge(left_half, right_half)

def merge(left, right):
    merged = []
    left_index = 0
    right_index = 0

    while left_index < len(left) and right_index < len(right):
        if left[left_index] < right[right_index]:
            merged.append(left[left_index])
            left_index += 1
        else:
            merged.append(right[right_index])
            right_index += 1

    while left_index < len(left):
        merged.append(left[left_index])
        left_index += 1

    while right_index < len(right):
        merged.append(right[right_index])
        right_index += 1

    return merged


def generate_random_matrix(user_matrix_element, user_min_limit=1, user_max_limit=10):
    return np.random.randint(user_min_limit, user_max_limit, size=(user_matrix_element))

user_matrix_element = int(input("Введите количество Элементы: "))
user_min_limit = int(input("Введите минимальный номер массива: "))
user_max_limit = int(input("Введите максимальное число в массиве :"))

matrix = generate_random_matrix(user_matrix_element, user_min_limit, user_max_limit)
print("Оригинал массива")
print(matrix)

print("\nОтсортированный массив по Турнирная сортировка")
sorted_array = tournament_sort(matrix)
print(sorted_array)

print("--- {0} ms ---".format(round(time.time() - start_time)*1000))


Введите количество Элементы:  15
Введите минимальный номер массива:  0
Введите максимальное число в массиве : 30


Оригинал массива
[21 19 17 21  4 18 13  4 19 27  9 11  4 25  7]

Отсортированный массив по Турнирная сортировка
[4, 4, 4, 7, 9, 11, 13, 17, 18, 19, 19, 21, 21, 25, 27]
--- 18000 ms ---


### Вывод
